# Generated by Django 4.0.5 on 2022-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
